//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandUpTimer.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StandUpTimer.Localization.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do not start at startup.
        /// </summary>
        public static string DontLaunchAtStartup {
            get {
                return ResourceManager.GetString("DontLaunchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fr.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run at startup.
        /// </summary>
        public static string LaunchAtStartup {
            get {
                return ResourceManager.GetString("LaunchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на min.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mo.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End of the working day. Time to relax!.
        /// </summary>
        public static string Notify_EndWorkDayNotify {
            get {
                return ResourceManager.GetString("Notify.EndWorkDayNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can sit down!.
        /// </summary>
        public static string Notify_GoSitNotify {
            get {
                return ResourceManager.GetString("Notify.GoSitNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It&apos;s time to get back on your feet!.
        /// </summary>
        public static string Notify_GoStandUpNotify {
            get {
                return ResourceManager.GetString("Notify.GoStandUpNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reminder.
        /// </summary>
        public static string Notify_Reminder {
            get {
                return ResourceManager.GetString("Notify.Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Notify_StartWorkDayNotify {
            get {
                return ResourceManager.GetString("Notify.StartWorkDayNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sa.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sitting.
        /// </summary>
        public static string Sitting {
            get {
                return ResourceManager.GetString("Sitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standing up.
        /// </summary>
        public static string StandingUp {
            get {
                return ResourceManager.GetString("StandingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No timer operation day selected.
        /// </summary>
        public static string Status_AllDaysUnsettedStatus {
            get {
                return ResourceManager.GetString("Status.AllDaysUnsettedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на at.
        /// </summary>
        public static string Status_At {
            get {
                return ResourceManager.GetString("Status.At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on Friday.
        /// </summary>
        public static string Status_OnFriday {
            get {
                return ResourceManager.GetString("Status.OnFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on Monday.
        /// </summary>
        public static string Status_OnMonday {
            get {
                return ResourceManager.GetString("Status.OnMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on Saturday.
        /// </summary>
        public static string Status_OnSaturday {
            get {
                return ResourceManager.GetString("Status.OnSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on Sunday.
        /// </summary>
        public static string Status_OnSunday {
            get {
                return ResourceManager.GetString("Status.OnSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on Thursday.
        /// </summary>
        public static string Status_OnThursday {
            get {
                return ResourceManager.GetString("Status.OnThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on Tuesday.
        /// </summary>
        public static string Status_OnTuesday {
            get {
                return ResourceManager.GetString("Status.OnTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on Wednesday.
        /// </summary>
        public static string Status_OnWednesday {
            get {
                return ResourceManager.GetString("Status.OnWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now is the time to sit. End of period at.
        /// </summary>
        public static string Status_SittingPeriodStatus {
            get {
                return ResourceManager.GetString("Status.SittingPeriodStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now is the time to stand. End of period at.
        /// </summary>
        public static string Status_StandUpPeriodStatus {
            get {
                return ResourceManager.GetString("Status.StandUpPeriodStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timer off.
        /// </summary>
        public static string Status_TimerNotWorkingStatus {
            get {
                return ResourceManager.GetString("Status.TimerNotWorkingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The timer will start.
        /// </summary>
        public static string Status_TimerWillStart {
            get {
                return ResourceManager.GetString("Status.TimerWillStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Su.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Th.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timer running time:.
        /// </summary>
        public static string TimerRunningTime {
            get {
                return ResourceManager.GetString("TimerRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на to.
        /// </summary>
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string TrayIcon_Exit {
            get {
                return ResourceManager.GetString("TrayIcon.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open window.
        /// </summary>
        public static string TrayIcon_OpenWindow {
            get {
                return ResourceManager.GetString("TrayIcon.OpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to open the options window.
        /// </summary>
        public static string TrayIconToolTip {
            get {
                return ResourceManager.GetString("TrayIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tu.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
